### ISSUE TITLE
Problem with Getting Started

### ISSUE THREAD

**Issue by JanAhrend** [meteoric/meteor-ionic#312]
I have a problem setting up meteoric. These are the steps that I take: 

1. meteor create myapp
2. I delete the three HTML/CSS/JS files in the folder and copy the content of this GitHub into the folder (including the hidden files). 
3. meteor add iron:router fourseven:scss@2.0.0 meteoric:ionic-sass meteoric:ionicons-sass meteoric:ionic 
4. meteor 

I receive the following error message: 
```javascript
=> Started proxy.                             
=> Started MongoDB.                           
W20150913-16:39:24.524(1)? (STDERR)           
W20150913-16:39:24.526(1)? (STDERR) /Users/janahrend/.meteor/packages/meteor-tool/.1.1.4.18x7yhk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150913-16:39:24.526(1)? (STDERR) 						throw(ex);
W20150913-16:39:24.526(1)? (STDERR) 						      ^
W20150913-16:39:24.526(1)? (STDERR) ReferenceError: Template is not defined
W20150913-16:39:24.527(1)? (STDERR)     at app/components/ionActionSheet/ionActionSheet.js:79:1
W20150913-16:39:24.527(1)? (STDERR)     at app/components/ionActionSheet/ionActionSheet.js:114:3
W20150913-16:39:24.527(1)? (STDERR)     at /Users/janahrend/Documents/05Engineering/meteor/_projects/02comrep/repcom/cleaninstall/.meteor/local/build/programs/server/boot.js:222:10
W20150913-16:39:24.527(1)? (STDERR)     at Array.forEach (native)
W20150913-16:39:24.527(1)? (STDERR)     at Function._.each._.forEach (/Users/janahrend/.meteor/packages/meteor-tool/.1.1.4.18x7yhk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150913-16:39:24.527(1)? (STDERR)     at /Users/janahrend/Documents/05Engineering/meteor/_projects/02comrep/repcom/cleaninstall/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

I have the same problem when trying to set up the three example applications (Producthunt etc.). 

(Or am I missing something fundamental here?)

**Comment by jorjordandan** [comment]
The easiest way to set up the example applications is just to clone their repos or download the zip files from their repositories, for instance the [contacts repo is here](https://github.com/meteoric/contacts). Then just run meteor. You may have to run meteor update if you get an error when you try to start them.

**Comment by JanAhrend** [comment]
Thank you for this! For some reason I assumed I had to create the meteor project first locally. I think I read it in some meteoric tutorial.

This is "fixed" then. Maybe we can add that to the Getting Started guide?
